In [2]:
import torch
import numpy as np

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,device=device, requires_grad=True)

In [5]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


**Common Initialization methods**

In [6]:
x = torch.empty(size=(3,3))
x = torch.zeros((3,3))
x = torch.rand((3,3))
x = torch.ones((3,3))
x = torch.eye(5,5)
x = torch.arange(start=0, end=5, step=1)
x = torch.linspace(start=0.1, end=1, steps=10)
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)
x = torch.empty(size=(1,5)).uniform_(0,1)
x = torch.diag(torch.ones(5))

**How to initialize and convert tensors ti other types (int, float, double)**

In [7]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


Array to Tensor Conversion

In [8]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

Tensor Math and Comparison Operations

In [9]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])


In [10]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)
z2 = torch.add(x,y)
z = x+y
z = x-y


In [11]:
z = torch.true_divide(x,y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [12]:
#Inplace operations
t = torch.zeros(3)
t.add_(x)
t+=x
print(t)

tensor([2., 4., 6.])


In [13]:
z = x.pow(2)
z = x**2

Matrix Multiplication

In [14]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) #2*3
x3 = x1.mm(x2)
print(x3)

tensor([[1.4890, 1.8544, 1.2055],
        [1.6049, 1.6866, 1.2896]])


In [15]:
#Matrix Exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[3.7936, 3.6309, 4.6495, 4.7988, 2.5858],
        [4.0491, 3.6766, 4.8338, 4.9453, 2.6238],
        [2.6356, 2.3673, 3.1040, 3.1732, 1.6803],
        [2.7276, 2.6100, 3.3616, 3.4581, 1.8636],
        [2.9145, 2.9137, 3.6719, 3.7993, 2.0549]])


In [16]:
#element wise
z = x*y
print(z)

tensor([ 9, 16, 21])


In [17]:
#dot product
z = torch.dot(x,y)
print(z)
print(x.dot(y))

tensor(46)
tensor(46)


Batch Matrix Multiplication

In [18]:
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)
# print(out_bmm)

Other Useful Tensor Operations 

In [19]:
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(),dim=0)
z = torch.eq(x, y)
sorted_y, indices = torch.sort(y, dim=0, descending=False)
z = torch.clamp(x, min=0, max=10)

x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x)
print(z)
z = torch.all(x)
print(z)

tensor(True)
tensor(False)


Tensor Indexing

In [21]:
batch_size = 10
features  = 25
x = torch.rand((batch_size, features))
print(x[0].shape)

torch.Size([25])


In [25]:
print(x[:,0])
print(x[2,0:10])
x[0,0] = 100

tensor([0.6067, 0.3585, 0.4561, 0.2488, 0.8898, 0.8318, 0.2964, 0.5615, 0.3436,
        0.6834])
tensor([0.4561, 0.5319, 0.0531, 0.9698, 0.8082, 0.4015, 0.5971, 0.6548, 0.3522,
        0.3790])


Fancy Indexing

In [28]:
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3,5))
print(x)
rows = torch.tensor(([1,0]))
cols = torch.tensor((4,0))
print(x[rows, cols])

tensor([2, 5, 8])
tensor([[0.4725, 0.3829, 0.5523, 0.2132, 0.7067],
        [0.6125, 0.8671, 0.4216, 0.7604, 0.7376],
        [0.9168, 0.3681, 0.8886, 0.3290, 0.2316]])
tensor([0.7376, 0.4725])


Advance Indexing

In [30]:
x = torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [33]:
print(torch.where(x>5,x,x*2))
print(x.unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
1


In [34]:
print(x.numel())

10


# Tensor Reshaping

In [39]:
x = torch.arange(9)
x_3x3 = x.view(3,3) # It needs contigious memory allocation
print(x_3x3)
x_3x3 = x.reshape(3,3)
y = x_3x3.t()
# print(y.view(9)) This is not possible because after transpose memory are not contigious
print(y.contiguous().view(9))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [42]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2), dim=0))  # row number will be increased
print(torch.cat((x1,x2),dim=1))   ## coloumn number will be increased

tensor([[0.8880, 0.1400, 0.2813, 0.5351, 0.3915],
        [0.7584, 0.2716, 0.2698, 0.0819, 0.2846],
        [0.2387, 0.1721, 0.9608, 0.3478, 0.6290],
        [0.0448, 0.0213, 0.5642, 0.7893, 0.5633]])
tensor([[0.8880, 0.1400, 0.2813, 0.5351, 0.3915, 0.2387, 0.1721, 0.9608, 0.3478,
         0.6290],
        [0.7584, 0.2716, 0.2698, 0.0819, 0.2846, 0.0448, 0.0213, 0.5642, 0.7893,
         0.5633]])


In [43]:
z = x1.view(-1)
print(z.shape)


torch.Size([10])


In [44]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch,-1)
print(z.shape)


torch.Size([64, 10])


In [45]:
z = x.permute(0,2,1)  # transpose is a special version of permute
print(z.shape)

torch.Size([64, 5, 2])


In [52]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x)

torch.Size([1, 10])
torch.Size([10, 1])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
